- name: Dnf dependencies
  ansible.builtin.dnf:
    name: dnf-automatic

- name: Remove yum-cron hourly
  ansible.builtin.file:
    state: absent
    path: "/etc/cron.hourly/0yum-hourly.cron"

- name: Remove yum-cron daily
  ansible.builtin.file:
    state: absent
    path: "/etc/cron.hourly/0yum-daily.cron"

- name: Notify script
  ansible.builtin.copy:
    src: notify_updates
    dest: /usr/local/bin/
    mode: "0755"

- name: Send datadog event
  ansible.builtin.copy:
    src: send_datadog_event.py
    dest: /usr/local/bin
    mode: "0755"

- name: Notify cron
  ansible.builtin.cron:
    name: notify_updates
    cron_file: notify_updates
    user: root
    minute: '0'
    job: "/usr/local/bin/notify_updates &>> /var/log/notify_updates.log"

- name: Datadog API token
  community.general.cronvar:
    name: DATADOG_API_TOKEN
    value: "%DATADOG_API_KEY_TEMPLATE%"
    cron_file: notify_updates

- name: Cluster
  community.general.cronvar:
    name: CLUSTER
    value: "%CLUSTER_TEMPLATE%"
    cron_file: notify_updates

- name: Stateless instance flag
  community.general.cronvar:
    name: STATELESS_INSTANCE
    value: "1"
    cron_file: notify_updates
