- name: yum dependencies
  yum:
    name: "{{ item }}"
  with_items:
    - jq
    - yum-cron

- name:
  pip:
    name: awscli

- name: remove yum-cron hourly
  file:
    state: absent
    path: "/etc/cron.hourly/0yum-hourly.cron"

- name: remove yum-cron daily
  file:
    state: absent
    path: "/etc/cron.hourly/0yum-daily.cron"

- name: notify script
  copy:
    src: notify_updates
    dest: /usr/local/bin/
    mode: 0755

- name: config file
  copy:
    src: yum-cron-notify.conf
    dest: /etc/yum/
    mode: 0644

- name: send datadog event
  copy:
    src: send_datadog_event.py
    dest: /usr/local/bin
    mode: 0755

- name: notify cron
  cron:
    cron_file: notify_updates
    user: root
    minute: 0
    job: "/usr/local/bin/notify_updates &>> /var/log/notify_updates.log"

- name: Jenkins job name for API
  cronvar:
    name: JENKINS_JOB_NAME
    value: "%JENKINS_JOB_NAME_TEMPLATE%"
    cron_file: notify_updates

- name: Datadog API token
  cronvar:
    name: DATADOG_API_TOKEN
    value: "%DATADOG_API_KEY_TEMPLATE%"
    cron_file: notify_updates
