- name: yum dependencies
  yum:
    name: "{{ item }}"
  with_items:
    - jq
    - yum-cron

- name:
  pip:
    name: awscli

- name: remove yum-cron hourly
  file:
    state: absent
    path: "/etc/cron.hourly/0yum-hourly.cron"

- name: remove yum-cron daily
  file:
    state: absent
    path: "/etc/cron.hourly/0yum-daily.cron"

- name: notify script
  copy:
    src: notify_updates
    dest: /usr/bin/
    mode: 0755

- name: config file
  copy:
    src: yum-cron-notify.conf
    dest: /etc/yum/
    mode: 0644

- name: notify cron
  cron:
    cron_file: notify_updates
    user: root
    minute: 0
    job: "/usr/bin/notify_updates &>> /var/log/notify_updates.log"

- cronvar:
    name: TOPIC_ARN
    value: "%NOTIFY_UPDATES_SNS_TOPIC%"
    cron_file: notify_updates

- cronvar:
    name: JENKINS_JOB_URL
    value: "%JENKINS_JOB_URL%"
    cron_file: notify_updates
