#!/bin/bash

set -e

if [ -z "$TOPIC_ARN" ]; then
    echo 'TOPIC_ARN must be set' >&1
    exit 1
fi

if [ "$TOPIC_ARN" == '%NOTIFY_UPDATES_SNS_TOPIC%' ]; then
    echo 'TOPIC_ARN contains placeholder, ignoring' >&1
    exit 0
fi

if [ -z "JENKINS_JOB_URL" ]; then
    echo 'JENKINS_JOB_URL must be set' >&1
    exit 1
fi

if [ "JENKINS_JOB_URL" == '%JENKINS_JOB_URL%' ]; then
    echo 'JENKINS_JOB_URL contains placeholder, ignoring' >&1
    exit 0
fi

metadata_url='http://169.254.169.254/latest/dynamic/instance-identity/document'
region=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone | sed 's/\(.*\)./\1/')

updates="$(/usr/sbin/yum-cron /etc/yum/yum-cron-notify.conf)"
if [[ ! -z "$updates" ]]; then
    /usr/local/bin/aws sns publish \
	--region "${region}" \
        --topic-arn "$TOPIC_ARN" \
        --message "$(
            echo "$updates" | jq -Rs "{
                instance: $(curl -s $metadata_url),
                jenkins_job_url: \"$JENKINS_JOB_URL\",
                updates: .
            }"
        )"
fi
