#!/bin/bash

set -eou pipefail

if [ -z "${DATADOG_API_TOKEN}" ]; then
    echo 'DATADOG_API_TOKEN must be set' >&1
    exit 1
fi

if [ "${DATADOG_API_TOKEN}" == '%DATADOG_API_KEY_TEMPLATE%' ]; then
    echo 'DATADOG_API_TOKEN contains placeholder, ignoring' >&1
    exit 0
fi

if [ -z "${JENKINS_JOB_NAME}" ]; then
    echo 'JENKINS_JOB_NAME must be set' >&1
    exit 1
fi

if [ "${JENKINS_JOB_NAME}" == '%JENKINS_JOB_NAME_TEMPLATE%' ]; then
    echo 'JENKINS_JOB_NAME contains placeholder, ignoring' >&1
    exit 0
fi

if [ -z "${STATELESS_INSTANCE}" ]; then
    echo 'STATELESS_INSTANCE should be set to 0 or 1' >&1
fi

updates="$(/usr/sbin/yum-cron /etc/yum/yum-cron-notify.conf)"
if [[ -n "${updates}" ]]; then
    /usr/local/bin/send_datadog_event.py "${updates}"
fi
